global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'inquiry-automation'
    replica: '1'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/alerts.yml'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application
  - job_name: 'inquiry_api'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'
          environment: 'development'

  # MLflow (doesn't expose Prometheus metrics by default)
  # - job_name: 'mlflow'
  #   static_configs:
  #     - targets: ['mlflow:5000']
  #       labels:
  #         service: 'mlflow'
  #         environment: 'development'

  # Airflow (doesn't expose Prometheus metrics by default)
  # - job_name: 'airflow'
  #   static_configs:
  #     - targets: ['airflow-webserver:8080']
  #       labels:
  #         service: 'airflow'
  #         environment: 'development'

  # PostgreSQL (requires postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']
  #       labels:
  #         service: 'postgres'
  #         environment: 'development'

  # Redis (requires redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']
  #       labels:
  #         service: 'redis'
  #         environment: 'development'

