apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automated-inquiries-processing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/automated_inquiries_processing
    targetRevision: HEAD
    path: k8s/helm
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: "latest"
        - name: image.repository
          value: "your-registry/automated-inquiries-processing"
  destination:
    server: https://kubernetes.default.svc
    namespace: inquiries-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
