apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      initContainers:
      - name: copy-dags
        image: busybox
        command: ['sh', '-c', 'cp -rL /dags-source/* /dags-dest/ && ls -la /dags-dest/']
        volumeMounts:
        - name: dags-source
          mountPath: /dags-source
        - name: dags
          mountPath: /dags-dest
      containers:
      - name: webserver
        image: airflow-ml:2.7.3
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        command: ["airflow", "webserver", "--port", "8080", "--host", "0.0.0.0"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql://postgres:postgres@postgresql.inquiries-system.svc.cluster.local:5432/airflow"
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/opt/airflow/dags"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: "airflow-secret-key-2024"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "sVy65SeclhVH4L71cdB4tJfI7aZptw-N6hXyEpobOnY="
        - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
          value: "True"
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
      volumes:
      - name: dags-source
        configMap:
          name: airflow-dags
      - name: dags
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      initContainers:
      - name: copy-dags
        image: busybox
        command: ['sh', '-c', 'cp -rL /dags-source/* /dags-dest/ && ls -la /dags-dest/']
        volumeMounts:
        - name: dags-source
          mountPath: /dags-source
        - name: dags
          mountPath: /dags-dest
      containers:
      - name: scheduler
        image: airflow-ml:2.7.3
        imagePullPolicy: Never
        command: ["airflow", "scheduler"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql://postgres:postgres@postgresql.inquiries-system.svc.cluster.local:5432/airflow"
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/opt/airflow/dags"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: "airflow-secret-key-2024"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "sVy65SeclhVH4L71cdB4tJfI7aZptw-N6hXyEpobOnY="
        - name: USE_RULE_BASED_CLASSIFICATION
          value: "false"  # Set to "true" for systems with <16GB Docker RAM
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
      volumes:
      - name: dags-source
        configMap:
          name: airflow-dags
      - name: dags
        emptyDir: {}

