apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-simple
  labels:
    app: fastapi-simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-simple
  template:
    metadata:
      labels:
        app: fastapi-simple
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: fastapi-simple
        image: fastapi-app:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgresql.inquiries-system.svc.cluster.local:5432/inquiry_automation"
        - name: REDIS_URL
          value: "redis://redis.inquiries-system.svc.cluster.local:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-simple
  labels:
    app: fastapi-simple
spec:
  selector:
    app: fastapi-simple
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
