apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: inquiries-system
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: python-app
        image: python:3.11-slim
        ports:
        - containerPort: 8000
        command: ["python"]
        args: ["-c", "import http.server; import socketserver; handler = http.server.SimpleHTTPRequestHandler; httpd = socketserver.TCPServer(('', 8000), handler); print('Server running on port 8000'); httpd.serve_forever()"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: inquiries-system
spec:
  selector:
    app: python-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30008
  type: NodePort
